### ISSUE TITLE
tasklist

### ISSUE THREAD

**Issue by WinfredWang** [WinfredWang/CilBlog#2]
## TODO List
- [ ] 1 校验使用策略模式完成，且前后端共用
- [ ] 2完成分页实现：前100条使用`skip`，后100使用时间戳方式实现，基于`article`发布时间
- [x] 3 完善markdown编辑器
- [x] 4 完善权限校验，使用302进行跳转
- [ ] 5 vue ts化 
- [ ] 6 优化UI
- [ ] 7 功能模块化，实现一键下线上线功能。比如下线评论模块等
- [ ] 8 增加日志collection，将操作记录，异常等信息持久化，便于日后统计
- [ ] 9 增加分类标签，在侧边栏展示出标签供用户过滤文章 
- [ ] 10 vue后台渲染
- [ ] 11 自动生成静态页面()

#### 管理台
- [ ] 关于管理
- [ ] 博客管理 - 新的文章
- [ ] 博客管理 - 分类管理
- [ ] 博客管理 - 文章管理
- [ ] 评论管理
- [ ] 留言管理
- [ ] 网站统计
- [ ] 缓存管理
- [ ] 异常管理
- [ ] 系统设置
